[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@aave-v3-core/contracts/=lib/aave-v3-core/contracts/',
    '@aave-v3-periphery/contracts/=lib/aave-v3-periphery/contracts/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@layerzerolabs/oapp-upgradeable/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/contracts/'
]

